export const ROUTES = {
  USER: {
    HOME: "/home",
    ABOUT: "/about",
    PRODUCT_LIST: "/products",
    PRODUCT_DETAIL: "/product/:id",
    CART: "/cart",
    CHECKOUT: "/checkout",
    SUCCESSPAY: "/successpay",
    PROFILE: "profile",
    ADDRESS: "profile/address",
    PASSWORD: "profile/change-password",
    USERINFO: "profile/user-info",
    ORDER_HISTORY: "profile/order-history",
    FAVORITE: "/profile/favorite-products",
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    USER_LIST: "/admin/users",
    CREATE_PRODUCT: "/admin/create-product",
    UPDATE_PRODUCT: "/admin/update-product/:id",
    PRODUCT_MANAGER: "/admin/products",
    ORDER_LIST: "/admin/orders",
  },
  LOGIN: "/login",
  REGISTER: "/register",
};
