export const ROUTES = {
  USER: {
    HOME: "/home",
    ABOUT: "/about",
    PRODUCT_LIST: "/products",
    PRODUCT_DETAIL: "/product/:id",
    CART: "/cart",
    CHECKOUT: "/checkout",
    SUCCESSPAY: "/successpay/:id",
    PROFILE: "profile",
    ADDRESS: "profile/address",
    CHANGS_PASSWORD: "/profile/change-password",
    USERINFO: "/profile/user-info",
    ORDER_HISTORY: "/profile/order-history",
    FAVORITE: "/profile/favorite-products",
    ABOUT: "/home/about",
    DELIVERY_PAYMENT: "/home/delivery-payment",
    CONTACT: "/home/contact",
    NEWS: "/home/news",
    GENEGAL: "/home/general",
    MAINTENANCE: "/home/maintenance",
    SHIPPING_POLICY: "/home/shipping-policy",
    PRIVACY_POLICY: "/home/privacy-policy",
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    USER_LIST: "/admin/users",
    CREATE_PRODUCT: "/admin/create-product",
    UPDATE_PRODUCT: "/admin/update-product/:id",
    PRODUCT_MANAGER: "/admin/products",
    ORDER_LIST: "/admin/orders",
  },
  LOGIN: "/login",
  REGISTER: "/register",
};
